<?php

namespace Tipddy\UPVBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscripcionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscripcionRepository extends EntityRepository
{
}